name: Pierrot Playground
on: [workflow_dispatch]
jobs:
  pierrot:
    name: Install Pierrot and Show Help
    runs-on: ubuntu-latest
    steps:
    - uses: sdkman/sdkman-action@master
      with:
        candidate: pierrot
        version: 0.9.9
    - run: pierrot --help
